Repository tensorflow/estimator, pull requests merged in 2019-03, with the labels that each got.

#22 Read all evaluation metrics from the summary file.
  tensorflow_estimator/python/estimator/early_stopping.py
Labels: XS, cla: yes, ready to pull

#19 minor spelling tweaks
  tensorflow_estimator/contrib/estimator/python/estimator/dnn_with_layer_annotations.py
  tensorflow_estimator/python/estimator/canned/linear.py
  tensorflow_estimator/python/estimator/head/binary_class_head.py
  tensorflow_estimator/python/estimator/head/multi_class_head.py
  tensorflow_estimator/python/estimator/head/multi_label_head.py
  tensorflow_estimator/python/estimator/run_config.py
Labels: S, cla: yes, ready to pull

#7 Add back-ticks around `None`s to `RunConfig` doc
  tensorflow_estimator/python/estimator/run_config.py
Labels: S, cla: yes, ready to pull

#26 cherry-pick build_pip_package and gitignore into r1.13 branch
  .bazelrc
  .gitignore
  tensorflow_estimator/tools/pip_package/build_pip_package.sh
Labels: M, cla: yes

#25 pip_package: modularize build script to allow distros to install more flexibly
  tensorflow_estimator/tools/pip_package/build_pip_package.sh
Labels: S, cla: yes, ready to pull

#24 Add bazelrc and gitignore
  .bazelrc
  .gitignore
Labels: S, cla: yes, ready to pull
