Repository tensorflow/estimator, pull requests merged in 2021-04, with the labels that each got.

#67 Change version to 2.5.0-rc0
  tensorflow_estimator/tools/pip_package/setup.py
Labels: cla: yes

#68 Enable tracing in estimator training
  tensorflow_estimator/python/estimator/BUILD
  tensorflow_estimator/python/estimator/estimator.py
  tensorflow_estimator/python/estimator/estimator_test.py
Labels: M, cla: yes, ready to pull

#71 Fix distribute link error in train_and_evaluate function
  tensorflow_estimator/python/estimator/training.py
Labels: XS, cla: yes, kokoro:force-run, ready to pull
